# Tables

In [1]:
import pandas as pd

In [2]:
# Load data
as_hegemony_v4 = pd.read_csv('as-pairs/as-hegemony/single-upstream-pairs-as-hegemony-v4.csv')
as_hegemony_v6 = pd.read_csv('as-pairs/as-hegemony/single-upstream-pairs-as-hegemony-v6.csv')
as_relationship_v4 = pd.read_csv(
    'as-pairs/as-relationship/single-upstream-pairs-as-relationship-v4.csv'
)
as_relationship_v6 = pd.read_csv(
    'as-pairs/as-relationship/single-upstream-pairs-as-relationship-v6.csv'
)
measured_v4 = pd.concat(
    [
        pd.read_csv('as-pairs/measured/backup-upstream-pairs-measured-v4.csv'),
        pd.read_csv('as-pairs/measured/default-route-pairs-measured-v4.csv'),
        pd.read_csv('as-pairs/measured/single-upstream-pairs-measured-v4.csv'),
    ]
)
measured_v6 = pd.concat(
    [
        pd.read_csv('as-pairs/measured/backup-upstream-pairs-measured-v6.csv'),
        pd.read_csv('as-pairs/measured/default-route-pairs-measured-v6.csv'),
        pd.read_csv('as-pairs/measured/single-upstream-pairs-measured-v6.csv'),
    ]
)
direct_pairs_v4 = pd.read_csv('as-pairs/as-hegemony/direct-pairs-v4.csv')
indirect_pairs_v4 = pd.read_csv('as-pairs/as-hegemony/indirect-pairs-v4.csv')
direct_pairs_v6 = pd.read_csv('as-pairs/as-hegemony/direct-pairs-v6.csv')
indirect_pairs_v6 = pd.read_csv('as-pairs/as-hegemony/indirect-pairs-v6.csv')
indirect_pairs_in_customer_cone_v4 = pd.read_csv(
    'as-pairs/as-hegemony/customer-cone/indirect-pairs-in-customer-cone-v4.csv'
)
indirect_pairs_not_in_customer_cone_v4 = pd.read_csv(
    'as-pairs/as-hegemony/customer-cone/indirect-pairs-not-in-customer-cone-v4.csv'
)
indirect_pairs_no_data_v4 = pd.read_csv(
    'as-pairs/as-hegemony/customer-cone/indirect-pairs-no-data-v4.csv'
)
downstream_dependency_ip_version = pd.read_csv('as-hegemony/downstream-dependency-ip-version.csv')
dual_stack_downstreams_upstream_relationship =pd.read_csv('as-hegemony/dual-stack-downstreams-upstream-relationships.csv')

## Table 1

In [3]:
symmetric_difference_v4 = pd.concat([as_hegemony_v4, as_relationship_v4], keys=['as_hegemony', 'as_relationship']).drop_duplicates(keep=False)
symmetric_difference_v6 = pd.concat([as_hegemony_v6, as_relationship_v6], keys=['as_hegemony', 'as_relationship']).drop_duplicates(keep=False)
table_1 = pd.DataFrame(
    [
        [
            'AS Hegemony',
            as_hegemony_v4['upstream'].nunique(),
            as_hegemony_v6['upstream'].nunique(),
            as_hegemony_v4['downstream'].nunique(),
            as_hegemony_v6['downstream'].nunique(),
            len(as_hegemony_v4),
            len(as_hegemony_v6),
        ],
        [
            'AS relationship',
            as_relationship_v4['upstream'].nunique(),
            as_relationship_v6['upstream'].nunique(),
            as_relationship_v4['downstream'].nunique(),
            as_relationship_v6['downstream'].nunique(),
            len(as_relationship_v4),
            len(as_relationship_v6),
        ],
        [
            'Overlap',
            len(set(as_hegemony_v4['upstream']).intersection(as_relationship_v4['upstream'])),
            len(set(as_hegemony_v6['upstream']).intersection(as_relationship_v6['upstream'])),
            len(set(as_hegemony_v4['downstream']).intersection(as_relationship_v4['downstream'])),
            len(set(as_hegemony_v6['downstream']).intersection(as_relationship_v6['downstream'])),
            len(pd.merge(as_hegemony_v4, as_relationship_v4, how='inner')),
            len(pd.merge(as_hegemony_v6, as_relationship_v6, how='inner')),
        ],
        [
            'AS Hegemony only',
            len(set(as_hegemony_v4['upstream']).difference(as_relationship_v4['upstream'])),
            len(set(as_hegemony_v6['upstream']).difference(as_relationship_v6['upstream'])),
            len(set(as_hegemony_v4['downstream']).difference(as_relationship_v4['downstream'])),
            len(set(as_hegemony_v6['downstream']).difference(as_relationship_v6['downstream'])),
            len(symmetric_difference_v4.loc['as_hegemony']),
            len(symmetric_difference_v6.loc['as_hegemony']),
        ],
        [
            'AS relationship only',
            len(set(as_relationship_v4['upstream']).difference(as_hegemony_v4['upstream'])),
            len(set(as_relationship_v6['upstream']).difference(as_hegemony_v6['upstream'])),
            len(set(as_relationship_v4['downstream']).difference(as_hegemony_v4['downstream'])),
            len(set(as_relationship_v6['downstream']).difference(as_hegemony_v6['downstream'])),
            len(symmetric_difference_v4.loc['as_relationship']),
            len(symmetric_difference_v6.loc['as_relationship']),
        ],
        [
            'Measured',
            measured_v4['upstream'].nunique(),
            measured_v6['upstream'].nunique(),
            measured_v4['downstream'].nunique(),
            measured_v6['downstream'].nunique(),
            len(measured_v4),
            len(measured_v6),
        ],
    ],
    columns=[
        '',
        'Upstreams (IPv4)',
        'Upstreams (IPv6)',
        'Downstreams (IPv4)',
        'Downstreams (IPv6)',
        'Pairs (IPv4)',
        'Pairs (IPv6)',
    ],
)
table_1

,,Upstreams (IPv4),Upstreams (IPv6),Downstreams (IPv4),Downstreams (IPv6),Pairs (IPv4),Pairs (IPv6)
0,AS Hegemony,7069,3832,36408,19058,46795,27290
1,AS relationship,6987,1721,32149,6189,32149,6189
2,Overlap,6587,1600,28869,4948,28771,4892
3,AS Hegemony only,482,2232,7539,14110,18024,22398
4,AS relationship only,400,121,3280,1241,3378,1297
5,Measured,689,419,6366,1079,6754,1154

## Table 2

In [4]:
table_2 = pd.DataFrame([
    [
        'Pairs',
        len(as_hegemony_v4),
        pd.NA,
        len(as_hegemony_v6),
        pd.NA
    ],
    [
        'Direct',
        len(direct_pairs_v4),
        len(direct_pairs_v4) / len(as_hegemony_v4) * 100,
        len(direct_pairs_v6),
        len(direct_pairs_v6) / len(as_hegemony_v6) * 100
    ],
    [
        'Indirect',
        len(indirect_pairs_v4),
        len(indirect_pairs_v4) / len(as_hegemony_v4) * 100,
        len(indirect_pairs_v6),
        len(indirect_pairs_v6) / len(as_hegemony_v6) * 100
    ],
    [
        '...in customer cone',
        len(indirect_pairs_in_customer_cone_v4),
        len(indirect_pairs_in_customer_cone_v4) / len(indirect_pairs_v4) * 100,
        pd.NA,
        pd.NA,
    ],
    [
        '...not in customer cone',
        len(indirect_pairs_not_in_customer_cone_v4),
        len(indirect_pairs_not_in_customer_cone_v4) / len(indirect_pairs_v4) * 100,
        pd.NA,
        pd.NA,
    ],
    [
        'Upstream not in data',
        len(indirect_pairs_no_data_v4),
        len(indirect_pairs_no_data_v4) / len(indirect_pairs_v4) * 100,
        pd.NA,
        pd.NA,
    ],
],
columns=['', 'IPv4', '%', 'IPv6', '%']
)
table_2

                             IPv4          %   IPv6         %
0                    Pairs  46795       <NA>  27290      <NA>
1                   Direct  36010  76.952666  18935  69.38439
2                 Indirect  10785  23.047334   8355  30.61561
3      ...in customer cone   9414    87.2879   <NA>      <NA>
4  ...not in customer cone   1362  12.628651   <NA>      <NA>
5     Upstream not in data      9   0.083449   <NA>      <NA>

## Table 3

In [5]:
single_stack_v4 = downstream_dependency_ip_version[downstream_dependency_ip_version['stack'] == 'single-v4']
single_stack_v6 = downstream_dependency_ip_version[downstream_dependency_ip_version['stack'] == 'single-v6']
dual_stack = downstream_dependency_ip_version[downstream_dependency_ip_version['stack'] == 'dual']
table_3 = pd.DataFrame(
    [
        [
            'Single stack IPv4',
            len(single_stack_v4),
            pd.NA,
            pd.NA,
            len(single_stack_v4),
        ],
        [
            'Single stack IPv6',
            pd.NA,
            len(single_stack_v6),
            pd.NA,
            len(single_stack_v6),
        ],
        [
            'Dual stack',
            len(dual_stack[dual_stack['dependency'] == 'v4-only']),
            len(dual_stack[dual_stack['dependency'] == 'v6-only']),
            len(dual_stack[dual_stack['dependency'] == 'both']),
            len(dual_stack)
        ],
        [
            'Total',
            len(downstream_dependency_ip_version[downstream_dependency_ip_version['dependency'] == 'v4-only']),
            len(downstream_dependency_ip_version[downstream_dependency_ip_version['dependency'] == 'v6-only']),
            len(downstream_dependency_ip_version[downstream_dependency_ip_version['dependency'] == 'both']),
            len(downstream_dependency_ip_version)
        ],
    ],
    columns=['', 'IPv4-only', 'IPv6-only', 'Both', 'Total']
)
table_3

                     IPv4-only IPv6-only  Both  Total
0  Single stack IPv4     26430      <NA>  <NA>  26430
1  Single stack IPv6      <NA>      5780  <NA>   5780
2         Dual stack      1454      4754  8524  14732
3              Total     27884     10534  8524  46942

In [6]:
cernet_downstreams = as_hegemony_v6[
    (as_hegemony_v6['upstream'] == 38255)  # CERNET main ASN
    & (as_hegemony_v6['downstream'].isin(single_stack_v6['downstream']))
]
print(
    f'CERNET downstreams: {len(cernet_downstreams)} ({len(cernet_downstreams) / len(single_stack_v6) * 100:.2f}%)'
)

CERNET downstreams: 4097 (70.88%)

## Table 4

In [7]:
relation_counts = dual_stack_downstreams_upstream_relationship['relation'].value_counts()
relation_pct = (
    dual_stack_downstreams_upstream_relationship['relation'].value_counts(normalize=True) * 100
)
table_4 = pd.DataFrame(
    [
        [
            'IPv4 = IPv6',
            relation_counts['equal'],
            relation_pct['equal'],
        ],
        [
            'IPv4 ∩ IPv6 = ∅',
            relation_counts['disjoint'],
            relation_pct['disjoint'],
        ],
        [
            'IPv4 ⊂ IPv6',
            relation_counts['v4-subset-of-v6'],
            relation_pct['v4-subset-of-v6'],
        ],
        [
            'IPv4 ⊃ IPv6 ',
            relation_counts['v6-subset-of-v4'],
            relation_pct['v6-subset-of-v4'],
        ],
        [
            'IPv4 ∆ IPv6 ≠ ∅ ',
            relation_counts['symmetric-difference-not-empty'],
            relation_pct['symmetric-difference-not-empty'],
        ],
    ],
    columns=['Upstream Set Relation', 'Downstreams', '%'],
)
table_4

  Upstream Set Relation  Downstreams          %
0           IPv4 = IPv6         7213  84.619897
1       IPv4 ∩ IPv6 = ∅          333   3.906617
2           IPv4 ⊂ IPv6          676   7.930549
3          IPv4 ⊃ IPv6           217   2.545753
4      IPv4 ∆ IPv6 ≠ ∅            85   0.997184