# Tables

In [1]:
import pandas as pd

In [2]:
def get_pairs(df: pd.DataFrame) -> set:
    return {(r.upstream, r.downstream) for r in df.itertuples()}

In [3]:
# Load data
as_hegemony_v4 = pd.read_csv('as-pairs/as-hegemony/single-upstream-pairs-as-hegemony-v4.csv')
as_hegemony_v6 = pd.read_csv('as-pairs/as-hegemony/single-upstream-pairs-as-hegemony-v6.csv')
as_relationship_v4 = pd.read_csv(
    'as-pairs/as-relationship/single-upstream-pairs-as-relationship-v4.csv'
)
as_relationship_v6 = pd.read_csv(
    'as-pairs/as-relationship/single-upstream-pairs-as-relationship-v6.csv'
)
measured_v4 = pd.concat(
    [
        pd.read_csv('as-pairs/measured/backup-upstream-pairs-measured-v4.csv'),
        pd.read_csv('as-pairs/measured/default-route-pairs-measured-v4.csv'),
        pd.read_csv('as-pairs/measured/single-upstream-pairs-measured-v4.csv'),
    ]
)
measured_v6 = pd.concat(
    [
        pd.read_csv('as-pairs/measured/backup-upstream-pairs-measured-v6.csv'),
        pd.read_csv('as-pairs/measured/default-route-pairs-measured-v6.csv'),
        pd.read_csv('as-pairs/measured/single-upstream-pairs-measured-v6.csv'),
    ]
)
direct_pairs_v4 = pd.read_csv('as-pairs/as-hegemony/direct-pairs-v4.csv')
indirect_pairs_v4 = pd.read_csv('as-pairs/as-hegemony/indirect-pairs-v4.csv')
direct_pairs_v6 = pd.read_csv('as-pairs/as-hegemony/direct-pairs-v6.csv')
indirect_pairs_v6 = pd.read_csv('as-pairs/as-hegemony/indirect-pairs-v6.csv')
indirect_pairs_in_customer_cone_v4 = pd.read_csv(
    'as-pairs/as-hegemony/customer-cone/indirect-pairs-in-customer-cone-v4.csv'
)
indirect_pairs_not_in_customer_cone_v4 = pd.read_csv(
    'as-pairs/as-hegemony/customer-cone/indirect-pairs-not-in-customer-cone-v4.csv'
)
indirect_pairs_no_data_v4 = pd.read_csv(
    'as-pairs/as-hegemony/customer-cone/indirect-pairs-no-data-v4.csv'
)
downstream_dependency_ip_version = pd.read_csv('as-hegemony/downstream-dependency-ip-version.csv')
dual_stack_downstreams_upstream_relationship = pd.read_csv(
    'as-hegemony/dual-stack-downstreams-upstream-relationships.csv'
)
sibling_classification_as_hegemony_v4 = pd.read_csv(
    'as-hegemony/sibling-classification-as-hegemony-v4.csv'
)
sibling_classification_measured_v4 = pd.read_csv('measured/sibling-classification-measured-v4.csv')
single_upstream_pairs_measured_v4 = pd.read_csv('as-pairs/measured/single-upstream-pairs-measured-v4.csv')
single_upstream_pairs_isp_v4 = get_pairs(
    pd.read_csv('as-pairs/measured/single-upstream-pairs-measured-v4.csv')
).intersection(get_pairs(pd.read_csv('as-pairs/measured/isp-pairs-v4.csv')))
sibling_classification_isp_v4 = sibling_classification_measured_v4[
    sibling_classification_measured_v4.apply(
        lambda r: (r['upstream'], r['downstream']) in single_upstream_pairs_isp_v4, axis='columns'
    )
]
downstreams_at_ixps_as_hegemony_v4 = pd.read_csv('as-hegemony/downstreams-at-ixps-as-hegemony-v4.csv')
hg_reachable_via_ixp_as_hegemony_v4 = pd.read_csv('as-hegemony/hg-reachable-via-ixp-as-hegemony-v4.csv')
downstreams_at_ixps_measured_v4 = pd.read_csv('measured/downstreams-at-ixps-measured-v4.csv')
hg_reachable_via_ixp_measured_v4 = pd.read_csv('measured/hg-reachable-via-ixp-measured-v4.csv')

## Table 1

In [4]:
symmetric_difference_v4 = pd.concat([as_hegemony_v4, as_relationship_v4], keys=['as_hegemony', 'as_relationship']).drop_duplicates(keep=False)
symmetric_difference_v6 = pd.concat([as_hegemony_v6, as_relationship_v6], keys=['as_hegemony', 'as_relationship']).drop_duplicates(keep=False)
table_1 = pd.DataFrame(
    [
        [
            'AS Hegemony',
            as_hegemony_v4['upstream'].nunique(),
            as_hegemony_v6['upstream'].nunique(),
            as_hegemony_v4['downstream'].nunique(),
            as_hegemony_v6['downstream'].nunique(),
            len(as_hegemony_v4),
            len(as_hegemony_v6),
        ],
        [
            'AS relationship',
            as_relationship_v4['upstream'].nunique(),
            as_relationship_v6['upstream'].nunique(),
            as_relationship_v4['downstream'].nunique(),
            as_relationship_v6['downstream'].nunique(),
            len(as_relationship_v4),
            len(as_relationship_v6),
        ],
        [
            'Overlap',
            len(set(as_hegemony_v4['upstream']).intersection(as_relationship_v4['upstream'])),
            len(set(as_hegemony_v6['upstream']).intersection(as_relationship_v6['upstream'])),
            len(set(as_hegemony_v4['downstream']).intersection(as_relationship_v4['downstream'])),
            len(set(as_hegemony_v6['downstream']).intersection(as_relationship_v6['downstream'])),
            len(pd.merge(as_hegemony_v4, as_relationship_v4, how='inner')),
            len(pd.merge(as_hegemony_v6, as_relationship_v6, how='inner')),
        ],
        [
            'AS Hegemony only',
            len(set(as_hegemony_v4['upstream']).difference(as_relationship_v4['upstream'])),
            len(set(as_hegemony_v6['upstream']).difference(as_relationship_v6['upstream'])),
            len(set(as_hegemony_v4['downstream']).difference(as_relationship_v4['downstream'])),
            len(set(as_hegemony_v6['downstream']).difference(as_relationship_v6['downstream'])),
            len(symmetric_difference_v4.loc['as_hegemony']),
            len(symmetric_difference_v6.loc['as_hegemony']),
        ],
        [
            'AS relationship only',
            len(set(as_relationship_v4['upstream']).difference(as_hegemony_v4['upstream'])),
            len(set(as_relationship_v6['upstream']).difference(as_hegemony_v6['upstream'])),
            len(set(as_relationship_v4['downstream']).difference(as_hegemony_v4['downstream'])),
            len(set(as_relationship_v6['downstream']).difference(as_hegemony_v6['downstream'])),
            len(symmetric_difference_v4.loc['as_relationship']),
            len(symmetric_difference_v6.loc['as_relationship']),
        ],
        [
            'Measured',
            measured_v4['upstream'].nunique(),
            measured_v6['upstream'].nunique(),
            measured_v4['downstream'].nunique(),
            measured_v6['downstream'].nunique(),
            len(measured_v4),
            len(measured_v6),
        ],
    ],
    columns=[
        '',
        'Upstreams (IPv4)',
        'Upstreams (IPv6)',
        'Downstreams (IPv4)',
        'Downstreams (IPv6)',
        'Pairs (IPv4)',
        'Pairs (IPv6)',
    ],
)
table_1

,,Upstreams (IPv4),Upstreams (IPv6),Downstreams (IPv4),Downstreams (IPv6),Pairs (IPv4),Pairs (IPv6)
0,AS Hegemony,7069,3832,36408,19058,46795,27290
1,AS relationship,6987,1721,32149,6189,32149,6189
2,Overlap,6587,1600,28869,4948,28771,4892
3,AS Hegemony only,482,2232,7539,14110,18024,22398
4,AS relationship only,400,121,3280,1241,3378,1297
5,Measured,689,419,6366,1079,6754,1154

## Table 2

In [5]:
table_2 = pd.DataFrame([
    [
        'Pairs',
        len(as_hegemony_v4),
        pd.NA,
        len(as_hegemony_v6),
        pd.NA
    ],
    [
        'Direct',
        len(direct_pairs_v4),
        len(direct_pairs_v4) / len(as_hegemony_v4) * 100,
        len(direct_pairs_v6),
        len(direct_pairs_v6) / len(as_hegemony_v6) * 100
    ],
    [
        'Indirect',
        len(indirect_pairs_v4),
        len(indirect_pairs_v4) / len(as_hegemony_v4) * 100,
        len(indirect_pairs_v6),
        len(indirect_pairs_v6) / len(as_hegemony_v6) * 100
    ],
    [
        '...in customer cone',
        len(indirect_pairs_in_customer_cone_v4),
        len(indirect_pairs_in_customer_cone_v4) / len(indirect_pairs_v4) * 100,
        pd.NA,
        pd.NA,
    ],
    [
        '...not in customer cone',
        len(indirect_pairs_not_in_customer_cone_v4),
        len(indirect_pairs_not_in_customer_cone_v4) / len(indirect_pairs_v4) * 100,
        pd.NA,
        pd.NA,
    ],
    [
        'Upstream not in data',
        len(indirect_pairs_no_data_v4),
        len(indirect_pairs_no_data_v4) / len(indirect_pairs_v4) * 100,
        pd.NA,
        pd.NA,
    ],
],
columns=['', 'IPv4', '%', 'IPv6', '%']
)
table_2

                             IPv4          %   IPv6         %
0                    Pairs  46795       <NA>  27290      <NA>
1                   Direct  36010  76.952666  18935  69.38439
2                 Indirect  10785  23.047334   8355  30.61561
3      ...in customer cone   9414    87.2879   <NA>      <NA>
4  ...not in customer cone   1362  12.628651   <NA>      <NA>
5     Upstream not in data      9   0.083449   <NA>      <NA>

## Table 3

In [6]:
single_stack_v4 = downstream_dependency_ip_version[downstream_dependency_ip_version['stack'] == 'single-v4']
single_stack_v6 = downstream_dependency_ip_version[downstream_dependency_ip_version['stack'] == 'single-v6']
dual_stack = downstream_dependency_ip_version[downstream_dependency_ip_version['stack'] == 'dual']
table_3 = pd.DataFrame(
    [
        [
            'Single stack IPv4',
            len(single_stack_v4),
            pd.NA,
            pd.NA,
            len(single_stack_v4),
        ],
        [
            'Single stack IPv6',
            pd.NA,
            len(single_stack_v6),
            pd.NA,
            len(single_stack_v6),
        ],
        [
            'Dual stack',
            len(dual_stack[dual_stack['dependency'] == 'v4-only']),
            len(dual_stack[dual_stack['dependency'] == 'v6-only']),
            len(dual_stack[dual_stack['dependency'] == 'both']),
            len(dual_stack)
        ],
        [
            'Total',
            len(downstream_dependency_ip_version[downstream_dependency_ip_version['dependency'] == 'v4-only']),
            len(downstream_dependency_ip_version[downstream_dependency_ip_version['dependency'] == 'v6-only']),
            len(downstream_dependency_ip_version[downstream_dependency_ip_version['dependency'] == 'both']),
            len(downstream_dependency_ip_version)
        ],
    ],
    columns=['', 'IPv4-only', 'IPv6-only', 'Both', 'Total']
)
table_3

                     IPv4-only IPv6-only  Both  Total
0  Single stack IPv4     26430      <NA>  <NA>  26430
1  Single stack IPv6      <NA>      5780  <NA>   5780
2         Dual stack      1454      4754  8524  14732
3              Total     27884     10534  8524  46942

In [7]:
cernet_downstreams = as_hegemony_v6[
    (as_hegemony_v6['upstream'] == 38255)  # CERNET main ASN
    & (as_hegemony_v6['downstream'].isin(single_stack_v6['downstream']))
]
print(
    f'CERNET downstreams: {len(cernet_downstreams)} ({len(cernet_downstreams) / len(single_stack_v6) * 100:.2f}%)'
)

CERNET downstreams: 4097 (70.88%)

## Table 4

In [8]:
relation_counts = dual_stack_downstreams_upstream_relationship['relation'].value_counts()
relation_pct = (
    dual_stack_downstreams_upstream_relationship['relation'].value_counts(normalize=True) * 100
)
table_4 = pd.DataFrame(
    [
        [
            'IPv4 = IPv6',
            relation_counts['equal'],
            relation_pct['equal'],
        ],
        [
            'IPv4 ∩ IPv6 = ∅',
            relation_counts['disjoint'],
            relation_pct['disjoint'],
        ],
        [
            'IPv4 ⊂ IPv6',
            relation_counts['v4-subset-of-v6'],
            relation_pct['v4-subset-of-v6'],
        ],
        [
            'IPv4 ⊃ IPv6 ',
            relation_counts['v6-subset-of-v4'],
            relation_pct['v6-subset-of-v4'],
        ],
        [
            'IPv4 ∆ IPv6 ≠ ∅ ',
            relation_counts['symmetric-difference-not-empty'],
            relation_pct['symmetric-difference-not-empty'],
        ],
    ],
    columns=['Upstream Set Relation', 'Downstreams', '%'],
)
table_4

  Upstream Set Relation  Downstreams          %
0           IPv4 = IPv6         7213  84.619897
1       IPv4 ∩ IPv6 = ∅          333   3.906617
2           IPv4 ⊂ IPv6          676   7.930549
3          IPv4 ⊃ IPv6           217   2.545753
4      IPv4 ∆ IPv6 ≠ ∅            85   0.997184

## Tables 5 & 9

In [9]:
# BGP view
borges_as_hegemony_v4 = sibling_classification_as_hegemony_v4['borges'].value_counts()
borges_as_hegemony_v4_pct = (
    sibling_classification_as_hegemony_v4['borges'].value_counts(normalize=True) * 100
)
as2org_as_hegemony_v4 = sibling_classification_as_hegemony_v4['as2org'].value_counts()
as2org_as_hegemony_v4_pct = (
    sibling_classification_as_hegemony_v4['as2org'].value_counts(normalize=True) * 100
)
iil_as2org_as_hegemony_v4 = sibling_classification_as_hegemony_v4['iil-as2org'].value_counts()
iil_as2org_as_hegemony_v4_pct = (
    sibling_classification_as_hegemony_v4['iil-as2org'].value_counts(normalize=True) * 100
)
# Measured
borges_measured_v4 = sibling_classification_measured_v4['borges'].value_counts()
borges_measured_v4_pct = (
    sibling_classification_measured_v4['borges'].value_counts(normalize=True) * 100
)
as2org_measured_v4 = sibling_classification_measured_v4['as2org'].value_counts()
as2org_measured_v4_pct = (
    sibling_classification_measured_v4['as2org'].value_counts(normalize=True) * 100
)
iil_as2org_measured_v4 = sibling_classification_measured_v4['iil-as2org'].value_counts()
iil_as2org_measured_v4_pct = (
    sibling_classification_measured_v4['iil-as2org'].value_counts(normalize=True) * 100
)
# ISPs
borges_isp_v4 = sibling_classification_isp_v4['borges'].value_counts()
borges_isp_v4_pct = sibling_classification_isp_v4['borges'].value_counts(normalize=True) * 100
as2org_isp_v4 = sibling_classification_isp_v4['as2org'].value_counts()
as2org_isp_v4_pct = sibling_classification_isp_v4['as2org'].value_counts(normalize=True) * 100
iil_as2org_isp_v4 = sibling_classification_isp_v4['iil-as2org'].value_counts()
iil_as2org_isp_v4_pct = (
    sibling_classification_isp_v4['iil-as2org'].value_counts(normalize=True) * 100
)

table_9 = pd.DataFrame(
    [
        [
            'BGP view',
            len(sibling_classification_as_hegemony_v4),
            'Borges',
            borges_as_hegemony_v4['sibling'],
            borges_as_hegemony_v4_pct['sibling'],
            borges_as_hegemony_v4['not_sibling'],
            borges_as_hegemony_v4_pct['not_sibling'],
        ],
        [
            '',
            len(sibling_classification_as_hegemony_v4),
            'AS2Org',
            as2org_as_hegemony_v4['sibling'],
            as2org_as_hegemony_v4_pct['sibling'],
            as2org_as_hegemony_v4['not_sibling'],
            as2org_as_hegemony_v4_pct['not_sibling'],
        ],
        [
            '',
            len(sibling_classification_as_hegemony_v4),
            'IIL-AS2Org',
            iil_as2org_as_hegemony_v4['sibling'],
            iil_as2org_as_hegemony_v4_pct['sibling'],
            iil_as2org_as_hegemony_v4['not_sibling'],
            iil_as2org_as_hegemony_v4_pct['not_sibling'],
        ],
        [
            'Measured',
            len(sibling_classification_measured_v4),
            'Borges',
            borges_measured_v4['sibling'],
            borges_measured_v4_pct['sibling'],
            borges_measured_v4['not_sibling'],
            borges_measured_v4_pct['not_sibling'],
        ],
        [
            '',
            len(sibling_classification_measured_v4),
            'AS2Org',
            as2org_measured_v4['sibling'],
            as2org_measured_v4_pct['sibling'],
            as2org_measured_v4['not_sibling'],
            as2org_measured_v4_pct['not_sibling'],
        ],
        [
            '',
            len(sibling_classification_measured_v4),
            'IIL-AS2Org',
            iil_as2org_measured_v4['sibling'],
            iil_as2org_measured_v4_pct['sibling'],
            iil_as2org_measured_v4['not_sibling'],
            iil_as2org_measured_v4_pct['not_sibling'],
        ],
        [
            'ISPs',
            len(sibling_classification_isp_v4),
            'Borges',
            borges_isp_v4['sibling'],
            borges_isp_v4_pct['sibling'],
            borges_isp_v4['not_sibling'],
            borges_isp_v4_pct['not_sibling'],
        ],
        [
            '',
            len(sibling_classification_isp_v4),
            'AS2Org',
            as2org_isp_v4['sibling'],
            as2org_isp_v4_pct['sibling'],
            as2org_isp_v4['not_sibling'],
            as2org_isp_v4_pct['not_sibling'],
        ],
        [
            '',
            len(sibling_classification_isp_v4),
            'IIL-AS2Org',
            iil_as2org_isp_v4['sibling'],
            iil_as2org_isp_v4_pct['sibling'],
            iil_as2org_isp_v4['not_sibling'],
            iil_as2org_isp_v4_pct['not_sibling'],
        ],
    ],
    columns=['Source', 'Total', 'Dataset', 'Siblings', '(%)', 'Not Siblings', '(%)'],
)
table_9

     Source  Total     Dataset  Siblings        (%)  Not Siblings        (%)
0  BGP view  46795      Borges      3279   7.007159         43516  92.992841
1            46795      AS2Org      2698   5.765573         44097  94.234427
2            46795  IIL-AS2Org      2933   6.267764         43862  93.732236
3  Measured   4835      Borges       455   9.410548          4380  90.589452
4             4835      AS2Org       398   8.231644          4437  91.768356
5             4835  IIL-AS2Org       439   9.079628          4396  90.920372
6      ISPs    183      Borges        40  21.857923           143  78.142077
7              183      AS2Org        33  18.032787           150  81.967213
8              183  IIL-AS2Org        41  22.404372           142  77.595628

## Table 6

In [10]:
num_su_downstreams_as_hegemony = as_hegemony_v4['downstream'].nunique()
num_su_downstreams_measured = single_upstream_pairs_measured_v4['downstream'].nunique()
su_downstreams_isp = {e[1] for e in single_upstream_pairs_isp_v4}
num_su_downstreams_isp = len(su_downstreams_isp)
downstreams_at_ixps_isp_v4 = downstreams_at_ixps_measured_v4[
    downstreams_at_ixps_measured_v4['downstream'].isin(su_downstreams_isp)
]
hg_reachable_via_ixp_isp_v4 = hg_reachable_via_ixp_measured_v4[
    hg_reachable_via_ixp_measured_v4['downstream'].isin(su_downstreams_isp)
]
table_6 = pd.DataFrame(
    [
        [
            'BGP view',
            num_su_downstreams_as_hegemony,
            downstreams_at_ixps_as_hegemony_v4['downstream'].nunique(),
            downstreams_at_ixps_as_hegemony_v4['downstream'].nunique()
            / num_su_downstreams_as_hegemony
            * 100,
            hg_reachable_via_ixp_as_hegemony_v4['downstream'].nunique(),
            hg_reachable_via_ixp_as_hegemony_v4['downstream'].nunique()
            / num_su_downstreams_as_hegemony
            * 100,
        ],
        [
            'Measured',
            num_su_downstreams_measured,
            downstreams_at_ixps_measured_v4['downstream'].nunique(),
            downstreams_at_ixps_measured_v4['downstream'].nunique()
            / num_su_downstreams_measured
            * 100,
            hg_reachable_via_ixp_measured_v4['downstream'].nunique(),
            hg_reachable_via_ixp_measured_v4['downstream'].nunique()
            / num_su_downstreams_measured
            * 100,
        ],
        [
            'ISPs',
            num_su_downstreams_isp,
            downstreams_at_ixps_isp_v4['downstream'].nunique(),
            downstreams_at_ixps_isp_v4['downstream'].nunique() / num_su_downstreams_isp * 100,
            hg_reachable_via_ixp_isp_v4['downstream'].nunique(),
            hg_reachable_via_ixp_isp_v4['downstream'].nunique() / num_su_downstreams_isp * 100,
        ],
    ],
    columns=['Source', 'Total', '...at IXPs', '(%)', '...HG peer', '(%)'],
)
table_6

     Source  Total  ...at IXPs        (%)  ...HG peer        (%)
0  BGP view  36408        4334  11.903977        3494   9.596792
1  Measured   4582         465  10.148407         398   8.686163
2      ISPs    174          59  33.908046          51  29.310345